# working with SQL

In [34]:
import pandas as pd

In [13]:
!pip install mysql.connector

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql.connector in c:\users\vasis\appdata\roaming\python\python312\site-packages (2.2.9)

In [3]:
# First, install the mysql-connector package
!pip install mysql-connector-python

# Then import it
import mysql.connector

# Now you can use mysql.connector to connect to MySQL databases

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in c:\users\vasis\appdata\roaming\python\python312\site-packages (9.4.0)

In [5]:
import mysql.connector

In [29]:
conn = mysql.connector.connect(host='localhost', user='root', password='', database='world')

In [58]:
pd.read_sql_query("SELECT * from countrylanguage WHERE language = 'English'", conn)

C:\Users\vasis\AppData\Local\Temp\ipykernel_8060\3729226650.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * from countrylanguage WHERE language = 'English'", conn)

   CountryCode Language IsOfficial  Percentage
0          ABW  English          F         9.5
1          AIA  English          T         0.0
2          ANT  English          F         7.8
3          ASM  English          T         3.1
4          ATG  English          T         0.0
5          AUS  English          T        81.2
6          BHR  English          F         0.0
7          BLZ  English          T        50.8
8          BMU  English          T       100.0
9          BRB  English          T         0.0
10         BRN  English          F         3.1
11         CAN  English          T        60.4
12         CCK  English          T         0.0
13         COK  English          F         0.0
14         CXR  English          T         0.0
15         CYM  English          T         0.0
16         DNK  English          F         0.3
17         FLK  English          T         0.0
18         GBR  English          T        97.3
19         GIB  English          T        88.9
20         GUM  English          T        37.5
21         HKG  English          T         2.2
22         IRL  English          T        98.4
23         ISL  English          F         0.0
24         JPN  English          F         0.1
25         KNA  English          T         0.0
26         KWT  English          F         0.0
27         LCA  English          T        20.0
28         LSO  English          T         0.0
29         MAC  English          F         0.5
30         MCO  English          F         6.5
31         MDV  English          F         0.0
32         MHL  English          T         0.0
33         MLT  English          T         2.1
34         MNP  English          T         4.8
35         MSR  English          T         0.0
36         MYS  English          F         1.6
37         NFK  English          T         0.0
38         NIU  English          T         0.0
39         NOR  English          F         0.5
40         NRU  English          T         7.5
41         NZL  English          T        87.0
42         PLW  English          T         3.2
43         PRI  English          F        47.4
44         SHN  English          T         0.0
45         SYC  English          T         3.8
46         TCA  English          T         0.0
47         TKL  English          T         0.0
48         TON  English          T         0.0
49         TTO  English          F        93.5
50         TUV  English          T         0.0
51         UMI  English          T         0.0
52         USA  English          T        86.2
53         VCT  English          T         0.0
54         VGB  English          T         0.0
55         VIR  English          T        81.7
56         VUT  English          T        28.3
57         WSM  English          T         0.6
58         ZAF  English          T         8.5
59         ZWE  English          T         2.2